### ISSUE TITLE
Example data with example input is not running ...

### ISSUE THREAD

**Issue by murpholinox** [charliebury/eTrack#28]
```
murph@eva02 ~/Repos/RIDL $ python ./runRIDL.py -i ./exampleInputFile.txt -pco 
Traceback (most recent call last):
  File "/home/murph/Repos/RIDL/./runRIDL.py", line 169, in <module>
    p.run()
  File "/home/murph/Repos/RIDL/lib/runRIDL_class.py", line 58, in run
    self.startLogFile()
  File "/home/murph/Repos/RIDL/lib/runRIDL_class.py", line 181, in startLogFile
    self.quickParseInputFile()
  File "/home/murph/Repos/RIDL/lib/runRIDL_class.py", line 171, in quickParseInputFile
    if 'dir' == l.split()[0]:
                ~~~~~~~~~^^^
IndexError: list index out of range
murph@eva02 ~/Repos/RIDL $ cat exampleInputFile.txt 
INITIALDATASET
name1 GH7-1
mtz1 /home/murph/Downloads/GH7-1.mtz
mtzlabels1 F_FROMDIALS1
pdb1 /home/murph/Downloads/GH7-1-fromRefmac.pdb
RfreeFlag1 FreeR_flag
dose1 1.11

LATERDATASET
name2 GH7-3,GH7-5,GH7-7,GH7-9,GH7-11
mtz2 /home/murph/Downloads/GH7-3.mtz,/home/murph/Downloads/GH7-5.mtz,/home/murph/Downloads/GH7-7.mtz,/home/murph/Downloads/GH7-9.mtz,/home/murph/Downloads/GH7-11.mtz
mtzlabels2 F_FROMDIALS3, F_FROMDIALS5, F_FROMDIALS7, F_FROMDIALS9, F_FROMDIALS11
dose2 5.43,9.75,14.1,18.4,22.7

PHASEDATASET
name3 GH7-1
mtz3 /home/murph/Downloads/GH7-1-fromRefmac.mtz
phaseLabel PHIC
FcalcLabel FC
murph@eva02 ~/Repos/RIDL $ python runRIDL.py --dependencies
Checking whether CCP4 program suite accessible...
---> success!

Checking required python packages...
---> success!

All dependencies have been successfully located
murph@eva02 ~/Downloads $ ls -lrt GH7*
-rw-------. 1 murph murph 5047844 Oct 25  2023 GH7-6.mtz
-rw-------. 1 murph murph 5072392 Oct 25  2023 GH7-7.mtz
-rw-------. 1 murph murph 5050504 Oct 25  2023 GH7-5.mtz
-rw-------. 1 murph murph 5111380 Oct 25  2023 GH7-11.mtz
-rw-------. 1 murph murph 5054532 Oct 25  2023 GH7-8.mtz
-rw-------. 1 murph murph 1145126 Oct 25  2023 GH7-1-fromRefmac.pdb
-rw-------. 1 murph murph 4995304 Oct 25  2023 GH7-1.mtz
-rw-------. 1 murph murph 5033404 Oct 25  2023 GH7-4.mtz
-rw-------. 1 murph murph 5092912 Oct 25  2023 GH7-9.mtz
-rw-------. 1 murph murph 5000572 Oct 25  2023 GH7-2.mtz
-rw-------. 1 murph murph 4469340 Oct 25  2023 GH7-1-fromRefmac.mtz
-rw-------. 1 murph murph 5026488 Oct 25  2023 GH7-3.mtz
-rw-------. 1 murph murph 5067984 Oct 25  2023 GH7-10.mtz

```

**Comment by murpholinox** [comment]
I was missing a ilne from the input file, not sure why. Probably an old input of mine.

**Comment by murpholinox** [comment]
Just for the record.... I was missing the dir output line
